# Generated by Django 3.1.13 on 2021-07-03 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_auto_20210703_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffpermissions',
            old_name='can_activate_session',
            new_name='can_manage_sessions',
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 45, 44, 304818)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 45, 44, 304818)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 45, 44, 304818)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 45, 44, 304818)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 13, 45, 44, 304818)),
        ),
    ]
