# Generated by Django 3.1.13 on 2021-07-05 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_auto_20210704_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipfinalresult',
            name='student_agrees',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='my_action',
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 34, 22, 40008)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 34, 22, 40008)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 34, 22, 48026)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 34, 22, 38014)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 34, 22, 43998)),
        ),
    ]
