# Generated by Django 3.1.13 on 2021-07-05 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_auto_20210705_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermissions',
            name='manage_CGPA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 39, 51, 217024)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 39, 51, 217024)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 39, 51, 228992)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 39, 51, 200069)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 39, 51, 221013)),
        ),
    ]
