# Generated by Django 3.1.13 on 2021-07-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20210705_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermissions',
            name='remove_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermissions',
            name='remove_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 50, 46, 555113)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 50, 46, 555113)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 50, 46, 559097)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 50, 46, 550124)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 50, 46, 556112)),
        ),
    ]
