# Generated by Django 3.1.13 on 2021-07-07 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_auto_20210707_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermissions',
            name='can_manage_internships',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 22, 9, 113957)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 22, 9, 113957)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 22, 9, 124928)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 22, 9, 107973)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 11, 22, 9, 118943)),
        ),
    ]
