# Generated by Django 3.1.13 on 2021-07-13 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0082_auto_20210707_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000, null=True)),
                ('message_time', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 999860))),
                ('engaged', models.BooleanField(default=False)),
                ('engaged_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 991879)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 991879)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 998863)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 985895)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 994871)),
        ),
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=10000, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
                ('message_time', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 20, 44, 45, 999860))),
                ('mess_time_str', models.CharField(max_length=10000, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_s', models.BooleanField(default=False)),
                ('chat_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.chatrequest')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
