# Generated by Django 3.2.8 on 2022-02-25 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_auto_20220225_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='students_required',
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 752303)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 753299)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 744748)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 744748)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 751305)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 742754)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 14, 34, 49, 746422)),
        ),
    ]
