# Generated by Django 3.2.12 on 2022-03-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_auto_20220225_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(max_length=16383),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=16383),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 699981)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='mess_time_str',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 701951)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='username',
            field=models.CharField(blank=True, max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 694948)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='internship_round',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 694948)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='message',
            field=models.CharField(max_length=16383),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='prev_round_for_result',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='round_name',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_name',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_position',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='prerequisite',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 699981)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 690944)),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 696911)),
        ),
    ]
