# Generated by Django 3.2.12 on 2022-03-08 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_auto_20220308_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 962270)),
        ),
        migrations.AlterField(
            model_name='chatresponse',
            name='message_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 963268)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 954085)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 954085)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 961268)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 950080)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 54, 9, 956084)),
        ),
    ]
