# Generated by Django 3.1.13 on 2021-07-02 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210503_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='unique_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='unique_code_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 643084)),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unique_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='unique_code_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 642088)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 643084)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 643084)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='signup_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 643084)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 642088)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 641396)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='signup_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 22, 16, 12, 641396)),
        ),
    ]
