# Generated by Django 3.2.12 on 2022-03-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20220225_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='complete_address',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='otp',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 686943)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 686943)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='signup_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 686943)),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='staff_first_name',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='staff_last_name',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_code',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='unique_code_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 686943)),
        ),
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='complete_address',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='otp',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 685946)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 684951)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='signup_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 685946)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='unique_code',
            field=models.CharField(max_length=16383, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='unique_code_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 15, 45, 46, 685946)),
        ),
    ]
